# Generated by Django 4.1.7 on 2023-05-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schoolname", models.CharField(max_length=100)),
                ("schoolprincipal", models.CharField(max_length=100)),
                ("schoollocation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.IntegerField(primary_key=True, serialize=False)),
                ("sname", models.CharField(max_length=100)),
                ("sage", models.IntegerField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Students",
                        to="app.school",
                    ),
                ),
            ],
        ),
    ]
